name: '{{ project-name }}'
description: '{{ project-name }}'

inputs:
  repository:
    description: Repository owner and repo name
    default: ${{ github.repository }}

  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}
  

runs:
  # https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/creating-a-docker-container-action
  using: "docker"
  image: "Dockerfile"

