name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        template: ["actions", "cli", "rocket-server"]

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: "Setup - Rust Toolchain"
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      env:
        TEMPLATE: ${{ matrix.template }}
      run: |
        set -e
        echo "Installing cargo-generate"
        cargo install cargo-generate

        echo "Using template: ${TEMPLATE}"
        mkdir -p "./output"
        cd "./output"
  
        echo "Generating project from template: ${TEMPLATE}"
        cargo generate \
          --path "../${TEMPLATE}" \
          --name "${TEMPLATE}"

