name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        template: ["actions", "cli", "web-server"]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cargo install cargo-generate
        cd "${{ matrix.template }}"
        cargo generate --test \
          -d project-name="sample" \
          -d description="A sample project"
